env:
  CIRRUS_CLONE_DEPTH: 1
  MSBUILDDISABLENODEREUSE: 1
  BR2_CCACHE: y
  BR2_CCACHE_DIR: .buildroot-ccache
  BR2_CCACHE_INITIAL_SETUP: 
  BR2_CCACHE_USE_BASEDIR: y

linux_x64_task:
  timeout_in: 90m
  container:
    cpu: 8
    memory: 8G
    image: gcc:11.2
  
  prepare_script:
    - apt-get update -qq
    - apt-get install -y cpio rsync bc
    # select webos_tv config
    - make lgtv_defconfig

  dl_cache:
    folder: dl
    # reupload the cache if content changed
    reupload_on_changes: true

  compile_cache:
    folder: .buildroot-ccache
    # reupload the cache if content changed
    reupload_on_changes: true

  build_script:
    - make sdk
  
  upload_caches:
    allow_failures: true
    - .buildroot-ccache
    - dl

  sdk_artifacts:
    path: output/images/*_sdk-buildroot.tar.gz
