env:
  CIRRUS_CLONE_DEPTH: 1
  MSBUILDDISABLENODEREUSE: 1
  BR2_CCACHE: y
  BR2_CCACHE_INITIAL_SETUP: 
  BR2_CCACHE_USE_BASEDIR: y

linux_x64_task:
  timeout_in: 90m
  container:
    cpu: 8
    memory: 8G
    image: gcc:11.2
  
  matrix:
    - name: LGTV config
      env:
        TOOLCHAIN_TARGET: webos
        DEFCONFIG: webos_tv_defconfig
        BR2_CCACHE_DIR: ${HOME}/.buildroot-ccache-webos

    - name: WebOS config
      env:
        TOOLCHAIN_TARGET: lgtv
        DEFCONFIG: lgtv_defconfig
        BR2_CCACHE_DIR: ${HOME}/.buildroot-ccache-lgtv

  prepare_script:
    - apt-get update -qq
    - apt-get install -y cpio rsync bc
    - make ${DEFCONFIG}

  dl_cache:
    folder: dl
    # reupload the cache if content changed
    reupload_on_changes: true

  compile_cache:
    folder: ${BR2_CCACHE_DIR}
    # reupload the cache if content changed
    reupload_on_changes: true

  build_script:
    - make sdk
  
  always:
    upload_caches:
      - compile
      - dl

  sdk_artifacts:
    path: output/images/*_sdk-buildroot.tar.gz
