################################################################################
#
# webos-userland
#
################################################################################

WEBOS_USERLAND_VERSION = 0.0.10
WEBOS_USERLAND_SITE = $(call github,webosbrew,webos-userland,$(WEBOS_USERLAND_VERSION))
WEBOS_USERLAND_LICENSE = Apache/MIT
WEBOS_USERLAND_INSTALL_STAGING = YES

WEBOS_USERLAND_PROVIDES = libegl libgles

WEBOS_USERLAND_POST_INSTALL_TARGET_HOOKS += WEBOS_USERLAND_EXTRA_LIBS_TARGET

WEBOS_USERLAND_POST_INSTALL_STAGING_HOOKS += WEBOS_USERLAND_EXTRA_LIBS_STAGING

define WEBOS_USERLAND_POST_TARGET_CLEANUP
	rm -Rf $(TARGET_DIR)/usr/src
endef
WEBOS_USERLAND_POST_INSTALL_TARGET_HOOKS += WEBOS_USERLAND_POST_TARGET_CLEANUP

ifeq ($(BR2_WAYLAND_EGL_SOVERSION_1),y)
WEBOS_USERLAND_CONF_OPTS += "-DWAYLAND_EGL_SOVERSION_1=ON"
endif

$(eval $(cmake-package))
