################################################################################
#
# libcapstone
#
################################################################################

LIBCAPSTONE_VERSION = 4.0.2
LIBCAPSTONE_SITE = $(call github,capstone-engine,capstone,$(LIBCAPSTONE_VERSION))

#LIBCAPSTONE_DEPENDENCIES =

ifeq ($(BR2_PACKAGE_LIBCAPSTONE_ARM),)
LIBCAPSTONE_CONF_OPTS += -DCAPSTONE_ARM_SUPPORT=OFF
endif
ifeq ($(BR2_PACKAGE_LIBCAPSTONE_ARM64),)
LIBCAPSTONE_CONF_OPTS += -DCAPSTONE_ARM64_SUPPORT=OFF
endif
ifeq ($(BR2_PACKAGE_LIBCAPSTONE_M680X),)
LIBCAPSTONE_CONF_OPTS += -DCAPSTONE_M680X_SUPPORT=OFF
endif
ifeq ($(BR2_PACKAGE_LIBCAPSTONE_M68K),)
LIBCAPSTONE_CONF_OPTS += -DCAPSTONE_M68K_SUPPORT=OFF
endif
ifeq ($(BR2_PACKAGE_LIBCAPSTONE_MIPS),)
LIBCAPSTONE_CONF_OPTS += -DCAPSTONE_MIPS_SUPPORT=OFF
endif
ifeq ($(BR2_PACKAGE_LIBCAPSTONE_MOS65XX),)
LIBCAPSTONE_CONF_OPTS += -DCAPSTONE_MOS65XX_SUPPORT=OFF
endif
ifeq ($(BR2_PACKAGE_LIBCAPSTONE_PPC),)
LIBCAPSTONE_CONF_OPTS += -DCAPSTONE_PPC_SUPPORT=OFF
endif
ifeq ($(BR2_PACKAGE_LIBCAPSTONE_SPARC),)
LIBCAPSTONE_CONF_OPTS += -DCAPSTONE_SPARC_SUPPORT=OFF
endif
ifeq ($(BR2_PACKAGE_LIBCAPSTONE_SYSZ),)
LIBCAPSTONE_CONF_OPTS += -DCAPSTONE_SYSZ_SUPPORT=OFF
endif
ifeq ($(BR2_PACKAGE_LIBCAPSTONE_XCORE),)
LIBCAPSTONE_CONF_OPTS += -DCAPSTONE_XCORE_SUPPORT=OFF
endif
ifeq ($(BR2_PACKAGE_LIBCAPSTONE_X86),)
LIBCAPSTONE_CONF_OPTS += -DCAPSTONE_X86_SUPPORT=OFF
endif
ifeq ($(BR2_PACKAGE_LIBCAPSTONE_TMS320C64X),)
LIBCAPSTONE_CONF_OPTS += -DCAPSTONE_TMS320C64X_SUPPORT=OFF
endif
ifeq ($(BR2_PACKAGE_LIBCAPSTONE_EVM),)
LIBCAPSTONE_CONF_OPTS += -DCAPSTONE_EVM_SUPPORT=OFF
endif

ifeq ($(BR2_PACKAGE_LIBCAPSTONE_DIET),y)
LIBCAPSTONE_CONF_OPTS += -DCAPSTONE_BUILD_DIET=ON
endif

LIBCAPSTONE_CONF_OPTS += -DCAPSTONE_BUILD_CSTOOL=OFF

$(eval $(cmake-package))
