################################################################################
#
# libcapstone
#
################################################################################

#LIBCAPSTONE_VERSION = 42fbce6c524a3a57748f9de2b5460a7135e236c1
#LIBCAPSTONE_SITE = $(call github,capstone-engine,capstone,$(LIBCAPSTONE_VERSION))
LIBCAPSTONE_VERSION = e98746112da0a40b2ccd0340db0d20cca5f97950
LIBCAPSTONE_SITE = $(call github,frida,capstone,$(LIBCAPSTONE_VERSION))
LIBCAPSTONE_SUPPORTS_IN_SOURCE_BUILD = NO
LIBCAPSTONE_INSTALL_TARGET = NO
LIBCAPSTONE_INSTALL_STAGING = YES

#LIBCAPSTONE_DEPENDENCIES =

ifeq ($(BR2_PACKAGE_LIBCAPSTONE_ARM),)
LIBCAPSTONE_CONF_OPTS += -DCAPSTONE_ARM_SUPPORT=OFF
endif
ifeq ($(BR2_PACKAGE_LIBCAPSTONE_ARM64),)
LIBCAPSTONE_CONF_OPTS += -DCAPSTONE_ARM64_SUPPORT=OFF
endif
ifeq ($(BR2_PACKAGE_LIBCAPSTONE_M680X),)
LIBCAPSTONE_CONF_OPTS += -DCAPSTONE_M680X_SUPPORT=OFF
endif
ifeq ($(BR2_PACKAGE_LIBCAPSTONE_M68K),)
LIBCAPSTONE_CONF_OPTS += -DCAPSTONE_M68K_SUPPORT=OFF
endif
ifeq ($(BR2_PACKAGE_LIBCAPSTONE_MIPS),)
LIBCAPSTONE_CONF_OPTS += -DCAPSTONE_MIPS_SUPPORT=OFF
endif
ifeq ($(BR2_PACKAGE_LIBCAPSTONE_MOS65XX),)
LIBCAPSTONE_CONF_OPTS += -DCAPSTONE_MOS65XX_SUPPORT=OFF
endif
ifeq ($(BR2_PACKAGE_LIBCAPSTONE_PPC),)
LIBCAPSTONE_CONF_OPTS += -DCAPSTONE_PPC_SUPPORT=OFF
endif
ifeq ($(BR2_PACKAGE_LIBCAPSTONE_SPARC),)
LIBCAPSTONE_CONF_OPTS += -DCAPSTONE_SPARC_SUPPORT=OFF
endif
ifeq ($(BR2_PACKAGE_LIBCAPSTONE_SYSZ),)
LIBCAPSTONE_CONF_OPTS += -DCAPSTONE_SYSZ_SUPPORT=OFF
endif
ifeq ($(BR2_PACKAGE_LIBCAPSTONE_XCORE),)
LIBCAPSTONE_CONF_OPTS += -DCAPSTONE_XCORE_SUPPORT=OFF
endif
ifeq ($(BR2_PACKAGE_LIBCAPSTONE_X86),)
LIBCAPSTONE_CONF_OPTS += -DCAPSTONE_X86_SUPPORT=OFF
endif
ifeq ($(BR2_PACKAGE_LIBCAPSTONE_TMS320C64X),)
LIBCAPSTONE_CONF_OPTS += -DCAPSTONE_TMS320C64X_SUPPORT=OFF
endif
ifeq ($(BR2_PACKAGE_LIBCAPSTONE_EVM),)
LIBCAPSTONE_CONF_OPTS += -DCAPSTONE_EVM_SUPPORT=OFF
endif

ifeq ($(BR2_PACKAGE_LIBCAPSTONE_DIET),y)
LIBCAPSTONE_CONF_OPTS += -DCAPSTONE_BUILD_DIET=ON
endif

LIBCAPSTONE_CONF_OPTS += \
	-DCAPSTONE_BUILD_CSTOOL=OFF \
	-DCAPSTONE_BUILD_TESTS=OFF

LIBCAPSTONE_CFLAGS += -fPIC

LIBCAPSTONE_CONF_OPTS += \
	-DCMAKE_C_FLAGS="$(TARGET_CFLAGS) $(LIBCAPSTONE_CFLAGS)" \
	-DCMAKE_CXX_FLAGS="$(TARGET_CXXFLAGS) $(LIBCAPSTONE_CFLAGS)"

$(eval $(cmake-package))
